[build]
builder = "NIXPACKS"
nixpacksConfigPath = "packages/backend/nixpacks.toml"

[deploy]
startCommand = "cd packages/backend && bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
