[build]
builder = "NIXPACKS"
nixpacksConfigPath = "packages/backend/nixpacks.toml"

[deploy]
startCommand = "cd packages/backend && echo '=== STARTING ===' && npx prisma migrate deploy && echo '=== MIGRATIONS DEPLOYED ===' && npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
