[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.ts", "**/*.js", "prisma/**/*"]

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
